namespace PropertyBot.Provider.VolksbankEnz
{
    internal static class EnvironmentConstants
    {
        public static string PROVIDER_VOLKSBANK_IMMOPOOL_GEOSL = "PROVIDER_VOLKSBANK_IMMOPOOL_GEOSL";
        public static string PROVIDER_VOLKSBANK_IMMOPOOL_PERIMETERS_IN_KM = "PROVIDER_VOLKSBANK_IMMOPOOL_PERIMETERS_IN_KM";
        public static string PROVIDER_VOLKSBANK_IMMOPOOL_OBJECT_CATEGORY = "PROVIDER_VOLKSBANK_IMMOPOOL_OBJECT_CATEGORY";
        public static string PROVIDER_VOLKSBANK_IMMOPOOL_CUSTOMER_ID = "PROVIDER_VOLKSBANK_IMMOPOOL_CUSTOMER_ID";
        public static string PROVIDER_VOLKSBANK_IMMOPOOL_LIMIT = "PROVIDER_VOLKSBANK_IMMOPOOL_LIMIT";
    }
}
